### ISSUE TITLE
DB connection

### ISSUE THREAD

**Issue by mastys100** [traprajith/open-school-CE#4]
This is the first message i get when i unpaclked it and opend it in my browser

"CDbConnection failed to open the DB connection....
May be you should go backorlogout"

Help me out

**Comment by traprajith** [comment]
Check for environment.php file under /protected/config 

if you found the file and db is not created, then delete the file and start installation by taking the root link in any browser.

**Comment by gulamquadir79** [comment]
I am getting this error everytime...
Fatal error: Uncaught ArgumentCountError: Too few arguments to function CMap::mergeArray(), 1 passed in D:\xampp\htdocs\protected\config\common.php on line 5 and exactly 2 expected in D:\xampp\htdocs\core\collections\CMap.php:275 Stack trace: #0 D:\xampp\htdocs\protected\config\common.php(5): CMap::mergeArray(Array) #1 D:\xampp\htdocs\core\base\CApplication.php(123): require('D:\\xampp\\htdocs...') #2 D:\xampp\htdocs\core\YiiBase.php(128): CApplication->__construct('D:\\xampp\\htdocs...') #3 D:\xampp\htdocs\core\YiiBase.php(100): YiiBase::createApplication('CWebApplication', 'D:\\xampp\\htdocs...') #4 D:\xampp\htdocs\index.php(51): YiiBase::createWebApplication('D:\\xampp\\htdocs...') #5 {main} thrown in D:\xampp\htdocs\core\collections\CMap.php on line 275

**Comment by traprajith** [comment]
Try latest version now.
